In [1]:
import numpy as np

In [2]:
arr = np.arange(0,25)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

Bracket indexing and selection

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [9]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [19]:
arr
#here data isnt copied,just the view of arr,to avoid memeory problems

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [21]:
#going explicit to copy
arr_copy = arr.copy()
arr_copy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [28]:
arr_2d = np.array(([5,10,5],[1,2,3],[4,5,6]))
#arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10,  5],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [29]:
arr_2d[1][1]

2

In [30]:
arr_2d[2,2]

6

In [34]:
arr_2d[:2,1:]

array([[10,  5],
       [ 2,  3]])

In [35]:
arr_2d[:1,1:]

array([[10,  5]])

In [36]:
arr_2d[2]

array([4, 5, 6])

In [37]:
arr_2d[2,:]

array([4, 5, 6])

In [56]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
arr2d[[2,4,6,8]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
arr_length = arr2d.shape[1]
arr_length

10

In [59]:
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [60]:
arr2d[[2,4,6,7,8,9]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [63]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [74]:
bool_type = arr>4
bool_type

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_type]

array([ 5,  6,  7,  8,  9, 10])

In [76]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
x = 2
arr[arr >> x]

array([1, 1, 1, 2, 2, 2, 2, 3, 3, 3])

In [83]:
x = 5
arr[arr >> x]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])