In [2]:
import numpy as np

In [3]:
import numpy as np

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
my_list = [1,2,3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros(3,5)

TypeError: data type not understood

In [15]:
np.zeros(((3,5,6)))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [16]:
np.ones(2)

array([1., 1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [19]:
np.linspace(0,11,50)

array([ 0.        ,  0.2244898 ,  0.44897959,  0.67346939,  0.89795918,
        1.12244898,  1.34693878,  1.57142857,  1.79591837,  2.02040816,
        2.24489796,  2.46938776,  2.69387755,  2.91836735,  3.14285714,
        3.36734694,  3.59183673,  3.81632653,  4.04081633,  4.26530612,
        4.48979592,  4.71428571,  4.93877551,  5.16326531,  5.3877551 ,
        5.6122449 ,  5.83673469,  6.06122449,  6.28571429,  6.51020408,
        6.73469388,  6.95918367,  7.18367347,  7.40816327,  7.63265306,
        7.85714286,  8.08163265,  8.30612245,  8.53061224,  8.75510204,
        8.97959184,  9.20408163,  9.42857143,  9.65306122,  9.87755102,
       10.10204082, 10.32653061, 10.55102041, 10.7755102 , 11.        ])

In [20]:
np.linspace(0,11,3)

array([ 0. ,  5.5, 11. ])

In [21]:
np.linspace(1,11,3)

array([ 1.,  6., 11.])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.eye(((3,3,3)))

TypeError: 'tuple' object cannot be interpreted as an integer

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(2)

array([0.16242725, 0.54294373])

In [26]:
np.random.randn(5,5)

array([[ 0.50802402,  0.37902468,  1.25040077, -0.5952611 ,  0.18407556],
       [-0.9605884 , -2.1034195 , -0.05304138,  0.17673771, -0.0488509 ],
       [ 1.19248828,  0.43434654,  0.0570695 ,  1.40742013, -0.06548556],
       [ 0.56831265,  0.37933445,  1.28487631,  0.38766784, -0.72626046],
       [ 0.11352565, -0.25906952, -0.7693595 , -3.51407009,  1.56583051]])

In [27]:
np.rand((2,2))

AttributeError: module 'numpy' has no attribute 'rand'

In [28]:
np.random.rand((2,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [29]:
np.random.rand(2,2)

array([[0.36474862, 0.82633186],
       [0.56276213, 0.75011894]])

In [30]:
np.random.randint(25)

3

In [31]:
np.random.randint(1,100,100)

array([95, 70, 53, 28, 82, 89, 38, 38, 61, 75, 13, 74, 68, 44, 14,  1, 23,
       58, 14, 88, 33, 44, 98,  4, 82, 26, 11, 53, 94, 51, 77, 21, 69, 60,
        3, 12, 20, 33, 75, 47, 15, 66, 40, 68, 23, 34, 98, 17, 66, 76, 19,
       59, 35, 61, 87, 86,  3, 37, 13, 49, 54, 13, 57, 90, 28, 55, 39, 35,
       18, 70, 22, 63, 16, 58, 53, 41, 88, 15,  8, 77, 69, 78, 84, 96, 45,
       59, 49, 23, 29, 86, 85,  2, 34, 26, 82, 38, 25, 42, 93, 41])

In [32]:
np.random.randint(1,100,101)

array([15, 49, 85, 39, 97,  5, 10, 14, 83,  5, 13, 72, 37, 82, 42, 96, 18,
       35, 62,  3, 94, 68, 42, 97, 15, 85, 35,  2, 88, 79, 30, 23, 43, 17,
       11,  8, 46, 87, 97, 85, 14, 59, 48, 93, 96, 12, 34, 94, 57, 16, 89,
       52, 71, 94,  8,  5, 62, 91, 23, 77, 13, 97, 70, 90,  7, 21, 83, 84,
        3, 48, 84, 56, 19,  8, 43, 67, 96, 85, 96, 41, 91, 42, 97, 57, 88,
       72, 93, 87, 43, 96, 88,  8, 31,  4, 82, 65, 89, 99, 70, 72, 32])

In [33]:
np.random.randint(1,100,10000)

array([90, 94, 14, ..., 94, 50, 57])

In [40]:
arr = np.arange(25)
arrp= np.random.randint(0,100,50)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arrp

array([43, 95, 58, 56, 89, 57, 58, 40, 59, 72, 47,  6, 79, 54, 66,  1, 99,
       54, 26, 64, 97,  5, 31, 27, 62, 55, 96,  3, 76, 64, 91, 76,  3, 33,
        4, 28, 45, 61,  3, 41, 45, 18, 91,  0,  4, 19, 16,  5, 33, 66])

In [43]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
ranarr = np.random.randint(0,50,10)

In [52]:
ranarr

array([27, 33, 29, 36, 44, 32, 45, 34, 36, 49])

In [53]:
ranarr.max()

49

In [54]:
ranarr.min()

27

In [55]:
arr.shape()

TypeError: 'tuple' object is not callable

In [56]:
arr.shape

(25,)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape.shape()

AttributeError: 'builtin_function_or_method' object has no attribute 'shape'

In [64]:
arr.reshape(25,1).shape

(25, 1)

In [69]:
arr.dtype

dtype('int32')

In [72]:
from numpy.random import randint

In [73]:
randint(1,100,5)

array([34, 45, 16, 85, 88])

all done